#!/usr/bin/zsh

######################
# jq_variables
######################
QZSHSETTINGS="$HOME/5q_env-qiuy/50_Environment/iqi_shells/oq_zsh/jq_settings/"
QZSHPATHWAYS="$HOME/4q50nqn_pathways/oq_zsh"

# autoload -Uz compinit
# compinit

# Check if zplug is installed
if [[ ! -d $HOME/.zplug ]]; then
    git clone https://github.com/zplug/zplug $HOME/.zplug
    source $HOME/.zplug/init.zsh && zplug update --self
fi

# Essential
source $HOME/.zplug/init.zsh
#
####################
# rq_installling
####################
# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
##############################
# jq_configuring
##############################
source $QZSHSETTINGS/jq_oqo_settings_plugins.zsh
source $QZSHSETTINGS/jq_oqo_settings_scripts.zsh
source $QZSHSETTINGS/jq_50_settings_environment.zsh
source $QZSHSETTINGS/jq_iqi_settings_bindings.zsh

####################
# bq_sourcing
####################
# Source zplug plugins and add commands to $PATH
zplug load --verbose
